-- 코드를 입력하세요
SELECT FOOD_TYPE,REST_ID,REST_NAME,FAVORITES FROM(
    SELECT FOOD_TYPE,REST_ID,REST_NAME,FAVORITES,
        ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS MX
    FROM REST_INFO) AS REST_VIEW WHERE MX = 1 GROUP BY FOOD_TYPE ORDER BY FOOD_TYPE DESC;