-- 코드를 입력하세요
WITH A as (SELECT FOOD_TYPE,REST_NAME,MAX(FAVORITES) AS MX FROM REST_INFO GROUP BY FOOD_TYPE)
SELECT R.FOOD_TYPE,R.REST_ID,R.REST_NAME,R.FAVORITES FROM REST_INFO AS R,A WHERE A.MX = R.FAVORITES AND R.FOOD_TYPE = A.FOOD_TYPE GROUP BY R.FOOD_TYPE ORDER BY R.FOOD_TYPE DESC;